### ISSUE TITLE
A different colour scheme

### ISSUE THREAD

**Issue by oxalorg** [prodicus/trumporate#13]
Great works with the project guys, I'm looking to contribute and perhaps I can start by giving some suggestions for the webpage design? 🐱 

Here's what I came up with, I haven't looked at the refresh/share button yet, but please give your feedback and if it's worthy of a PR ^_^!

![](https://oxal.org/img/s/2017-06/1497681584.png)

**Comment by prodicus** [comment]
@oxalorg Great work imo 💯 
What do you think @riturajDas 

To give context here is the current one

<img width="1440" alt="screen shot 2017-06-17 at 12 23 41 pm" src="https://user-images.githubusercontent.com/4672518/27250889-f650d78e-5357-11e7-9dd7-b3aae7b5932b.png">

**Comment by riturajDas** [comment]
Hello @oxalorg, whatsup!?
I really like the new color scheme. It has a nice pop to it 👍🏽
but is it like teal-ish only for PC screens? or something else
![whatsapp image 2017-06-17 at 2 34 04 pm](https://user-images.githubusercontent.com/20974909/27251739-f4565cc0-536a-11e7-9c11-6e9e20eaff46.jpeg)
the header text is black. Advise.

**Comment by oxalorg** [comment]
@riturajDas Check it out on localhost, my changes aren't merged so they shouldn't be live yet. (It could also be your cache)

Yeah the buttons are pushed below the fold when the rant is more than 2-3 lines. It needs some fixing, will make an issue up if the current PR gets merged.

**Comment by riturajDas** [comment]
@oxalorg ohh accha okie👍🏽

**Comment by prodicus** [comment]
Great work guys! @oxalorg @riturajDas 

So just for reference, I am putting here the current iteration
<center><img width="1440" alt="screen shot 2017-06-17 at 4 14 48 pm" src="https://user-images.githubusercontent.com/4672518/27252292-1d4bf1f0-5378-11e7-9edd-38e7a5d59863.png"></center?

<center><img width="380" alt="screen shot 2017-06-17 at 4 14 36 pm" src="https://user-images.githubusercontent.com/4672518/27252294-25213570-5378-11e7-9141-a01a3ea70b57.png"></center>

**Comment by prodicus** [comment]
Closing this issue as the color scheme has been decided. Feel free to open it if anything is left out

**Comment by prodicus** [comment]
@oxalorg Add your name to the footer and the contributor's list 😄

**Comment by riturajDas** [comment]
😃yeah was about to suggest the same🤘🏽
- where do u guys think the Markovipy name should go? or do we put the logo somewhere? thoughts?

**Comment by prodicus** [comment]
> where do u guys think the Markovipy name should go? or do we put the logo somewhere? thoughts?

+1 

Maybe just beneath the current footer in a new line? Or somewhere else?

the logo is here if someone is curious [http://i.imgur.com/cTY2kTK.png](http://i.imgur.com/cTY2kTK.png)

**Comment by riturajDas** [comment]
## README.md
![screen shot 2017-06-17 at 7 50 06 pm](https://user-images.githubusercontent.com/20974909/27253726-7fc5b6da-5397-11e7-93e1-acab8c5b2f5a.jpg)

**Comment by prodicus** [comment]
@riturajDas Add the ^ to README.md
